### ISSUE TITLE
security

### ISSUE THREAD

**Issue by alok-sharma-github** [mhamzashaikh/React-Inventory-Management-System#4]
@mhamzashaikh in `*Backend/models/index.js*` your MongoDB Uri is visible. I think you should consider hiding it. I don't think it is a good coding practice. However, if it is intentional then it's okay. Thankyou.

**Comment by mhamzashaikh** [comment]
Thank you for pointing that out! At that time, I hadn’t implemented dotenv in the project to manage environment variables but in the next update I'll ensure the repository is updated accordingly. 
Appreciate your feedback!
